CookBook/urls.py
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),

    path('', views.Home.as_view(), name='Home'),
    path('admin/', admin.site.urls),
    path('maintenance', views.Maintenance.as_view(), name='Maintenance'),
    path('recipe/', include('recipe.urls')),
    path('user/', include('user.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
]

recipe/urls.py
from django.urls import path
from . import views

app_name = 'recipe'

urlpatterns = [
    path('<int:pk>/', views.RecipeDetail.as_view(), name='recipe_detail'),
    path('', views.RecipeList.as_view(), name='recipe_list'),

    path('create/form_1', views.recipe_create_1, name='recipe_create_1'),
    path('create/form_2', views.recipe_create_2, name='recipe_create_2'),
    path('create/form_3', views.recipe_create_3, name='recipe_create_3'),
    path('create/form_4', views.recipe_create_4, name='recipe_create_4'),
    path('create/form_5', views.recipe_create_5, name='recipe_create_5'),

    path('edit/<int:pk>', views.RecipeDetailEdit.as_view(), name='recipe_update'),
    path('delete/<int:pk>', views.RecipeDelete.as_view(), name='recipe_delete'),

    path('title_update/<int:pk>', views.TitleUpdate.as_view(), name='title_update'),
    path('content_update/<int:pk>', views.ContentUpdate.as_view(), name='content_update'),
    path('image_update/<int:pk>', views.ImageUpdate.as_view(), name='image_update'),

    path('ingredients_update/<int:pk>', views.IngredientUpdate.as_view(), name='ingredient_update'),
    path('ingredients_update_empty/<int:pk>', views.IngredientUpdateWithExtra.as_view(), name='ingredient_update_empty'),

    path('tag_update/<int:pk>', views.TagUpdate.as_view(), name='tag_update'),
    path('tag_update_empty/<int:pk>', views.TagUpdateWithExtra.as_view(), name='tag_update_empty'),

    path('comment_update/<int:pk>', views.CommentUpdate.as_view(), name='comment_update'),
    path('comment_delete/<int:pk>', views.CommentDelete.as_view(), name='comment_delete'),



]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('profile/<int:pk>/', views.UserDetail.as_view(), name='user_profile'),
    path('list', views.UserList.as_view(), name='user_list'),
    path('signup', views.UserCreate.as_view(), name='signup'),
    path('user-edit/<int:pk>', views.UserUpdate.as_view(), name='user_update'),
    path('delete-profile/<int:pk>', views.UserDelete.as_view(), name='user_delete'),

    path('edit-profile/<int:pk>', views.UserProfileUpdate.as_view(), name='profile_update'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name="author_profile", on_delete=models.CASCADE)
    description = models.TextField(blank=True, null=True)
    picture = models.ImageField(upload_to='static/images/users',
                                blank=True, null=True)

    def __str__(self):
        return f'{self.user}'

user/forms.py
from django import forms
from django.contrib.auth.models import User
from user.models import UserProfile
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from crispy_forms.helper import FormHelper


class UserCForm(UserCreationForm):
    helper = FormHelper()
    helper.form_id = 'user-crispy-form'
    helper.form_method = 'POST'

    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(UserCForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        user.save()
        UserProfile.objects.create(
            user=user, description=""
        )
        return user


class UserUForm(UserChangeForm):
    helper = FormHelper()
    helper.form_id = 'user-crispy-form'
    helper.form_method = 'POST'

    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password")

    def save(self, commit=True):
        user = super(UserUForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['description', 'picture']

user/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.admin.views.decorators import staff_member_required
from django.core.exceptions import ObjectDoesNotExist
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import TemplateView, DetailView, ListView, CreateView, UpdateView, DeleteView
from user.forms import UserCForm, UserUForm, UserProfileForm
from django.contrib.auth.models import User
from user.models import UserProfile
from recipe.models import RecipePost
from django.urls import reverse_lazy
from django.contrib import messages
from django.shortcuts import render, redirect


# Create your views here.


class UserDetail(DetailView):
    model = User
    template_name = "user_detail.html"

    def get_context_data(self, **kwargs):
        context = super(UserDetail, self).get_context_data(**kwargs)
        user = User.objects.get(pk=self.kwargs['pk'])
        context['detail_user'] = user
        context['user'] = self.request.user
        try:
            context['profile'] = UserProfile.objects.get(user=user.pk)
        except self.model.DoesNotExist:
            raise ObjectDoesNotExist('User Profile does not exist')
        context['recipes'] = RecipePost.objects.filter(author=UserProfile.objects.get(user=user.pk))
        return context


@method_decorator(staff_member_required, name='dispatch')
class UserList(LoginRequiredMixin, ListView):
    model = User
    template_name = "user_list.html"


class UserCreate(CreateView):
    model = User
    form_class = UserCForm
    template_name = "user_create.html"
    success_url = reverse_lazy('Home')


class UserUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = User
    template_name = "user_update.html"
    form_class = UserUForm

    def test_func(self):
        obj = self.get_object()
        return obj.pk == self.request.user.pk or self.request.user.is_staff

    def get_success_url(self):
        return reverse_lazy('user:user_profile', kwargs={'pk': self.request.user.id})


@method_decorator(staff_member_required, name='dispatch')
class UserDelete(LoginRequiredMixin, DeleteView):
    model = User
    template_name = "user_delete.html"
    success_url = reverse_lazy('user:user_list')


class UserProfileUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = UserProfile
    template_name = "profile_update.html"
    form_class = UserProfileForm

    def test_func(self):
        obj = self.get_object()
        return obj.user.pk == self.request.user.pk or self.request.user.is_staff

    def get_success_url(self):
        return reverse_lazy('user:user_profile', kwargs={'pk': self.request.user.id})

user/templates/profile_update.html
{% extends 'base_manipulate.html' %}

{% load crispy_forms_tags %}

{% block title %} Edit Profile {% endblock %}

{% block header %}
Edit profile
{% endblock %}

{% block form_buttons %}
    <button type="submit"><i class="bi bi-check-lg"></i> Confirm</button>
    <a href="{% url 'user:user_profile' object.user.pk %}"><button type="button"><i class="bi bi-x-lg"></i><span class="removable-sm"> Undo</span></button></a>
{% endblock %}

user/templates/user_create.html
{% extends 'base_manipulate.html' %}

{% block title %} Sign up {% endblock %}

{% block header %}
Sign up
{% endblock %}

{% block form_buttons %}
    <button type="submit"><i class="bi bi-check-lg"></i> Confirm</button>
    <a href="{% url 'Home' %}"><button type="button"><i class="bi bi-x-lg"></i><span class="removable-sm"> Undo</span></button></a>
{% endblock %}

user/templates/user_delete.html
{% extends 'base_manipulate.html' %}

{% block title %} Delete User {% endblock %}

{% block header %}
Delete User
{% endblock %}

{% block extras %}
    <p>Are you sure you want to delete this user? <b>This action cannot be undone</b></p>
    <table>
        <tr><td>Username</td><td>{{object.username}}</td></tr>
        <tr><td>Email</td><td>{{object.email}}</td></tr>
        <tr><td>Admin</td><td>{{object.admin}}</td></tr>
    </table>
{% endblock %}

{% block form_buttons %}
    <button type="submit"><i class="bi bi-check-lg"></i> Confirm</button>
    <a href="{% url 'user:user_list' %}"><button type="button"><i class="bi bi-x-lg"></i><span class="removable-sm"> Undo</span></button></a>
{% endblock %}

user/templates/user_detail.html
{% extends 'base_evolved.html' %}
{% load static %}
{% load ratings %}

{% block title %} {{detail_user.username|capfirst}} {% endblock %}

{% block header %}
{{detail_user.username|capfirst}}
{% endblock %}

{% block content %}
<div>
    <div class="row">
        <div class="col-md-2 col-sm-12 my-2 d-flex align-items-center justify-content-center">
            {% if not profile.picture %}
                <img class="round center default-image profile-pic-lg" src="https://heliosgarden.it/wp-content/plugins/all-in-one-seo-pack/images/default-user-image.png">
            {% else %}
                <img class="round center profile-pic-lg" src='{{ profile.picture.url }}'>
            {% endif %}
        </div>
        <div class="col-md-10 col-sm-12">
            <h2 class="amatic">
                {% if detail_user.is_staff %}
                    <i class="bi bi-star-fill mr-2"></i>
                {% else %}
                    <i class="bi bi-user-fill mr-2"></i>
                {% endif %}
                {{detail_user.username}}
            </h2>

            <p>Email: <i>{{detail_user.email}}</i></p>
        </div>
    </div>

    <div class="row">
        <p class="text-justify mx-3">{{profile.description}}</p>
    </div>

    {% if user.pk == object.pk or user.is_staff %}
        <a href="{% url 'user:user_update' detail_user.pk %}"class="btn btn-primary mt-2 mb-4"><i class="bi bi-person"></i><span class="removable-md"> Change email or password</span></a>
        <a href="{% url 'user:profile_update' profile.pk %}"class="btn btn-primary mt-2 mb-4"><i class="bi bi-pencil"></i><span class="removable-md"> Add a description or a picture</span></a>
    {% endif %}
    {% if user.is_staff %}
        <a href="{% url 'user:user_list' %}"class="btn btn-primary mt-2 mb-4"><i class="bi bi-arrow-left"></i><span class="removable-md"> Back to user list</span></a>
    {% endif %}

    <h2 class="amatic">Recipes from {{detail_user.username}}</h2>
    <div class="row center align-items-center mb-4">
        {% if recipes %}
            {% for recipe in recipes %}
                <a href="{% url 'recipe:recipe_detail' recipe.pk %}"  class="col-md-3 col-sm-6 p-1">
                    <div class="card">
                        {% if not recipe.image %}
                            <img class="card-img-top center default-image" src="{% static 'images/Logo.png' %}">
                        {% else %}
                            <img class="card-img-top center" src='{{ recipe.image.url }}' alt="Card image cap">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{recipe.title}}</h5>
                            <p class="card-text font-italic">{{recipe.author}}</p>
                            {% ratings recipe %}
                        </div>
                    </div>
                </a>
            {% endfor %}
        {% else %}
            <p class="mx-3">There are no recipes by this user</p>
        {% endif %}
    </div>
</div>
{% endblock %}

user/templates/user_list.html
{% extends 'base_list.html' %}

{% block list_title %} User list {% endblock %}

{% block list_header %}
User list
{% endblock %}

{% block list_content %}
    <table class="table-striped my-3">
        <thead class="thead-dark"><tr><th>Username</th><th>Email</th><th>Status</th><th></th></tr></thead>
        {% for u in object_list %}
            <tr>
                <td>{{u.username}}</td>
                <td>{{u.email}}</td>
                <td>
                    {% if u.is_staff %}
                        <i class="bi bi-star-fill"></i> Admin
                    {% else %}
                        <i class="bi bi-user-fill"></i> User
                    {% endif %}
                </td>
                <td class="menu-right">
                    <a href="{% url 'user:user_profile' u.pk %}" class="btn btn-primary"><i class="bi bi-eye"></i><span class="removable-md"> Visualize</span></a>
                    <a href="{% url 'user:user_delete' u.pk %}" class="btn btn-primary btn-delete"><i class="bi bi-trash"></i><span class="removable-md"> Delete</span></a>
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

{% block post_extra %}
    <a href="{% url 'user:signup' %}"class="btn btn-primary mt-4"><i class="bi bi-plus-lg"></i><span class="removable-md"> New recipe</span></a>
{% endblock %}

user/templates/user_update.html
{% extends 'base_manipulate.html' %}

{% load crispy_forms_tags %}

{% block title %} Edit Profile {% endblock %}

{% block header %}
Edit profile
{% endblock %}

{% block form_buttons %}
    <button type="submit"><i class="bi bi-check-lg"></i> Confirm</button>
    <a href="{% url 'user:user_profile' object.pk %}"><button type="button"><i class="bi bi-x-lg"></i><span class="removable-sm"> Undo</span></button></a>
{% endblock %}