CookBook/urls.py
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),

    path('', views.Home.as_view(), name='Home'),
    path('admin/', admin.site.urls),
    path('maintenance', views.Maintenance.as_view(), name='Maintenance'),
    path('recipe/', include('recipe.urls')),
    path('user/', include('user.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
]

recipe/urls.py
from django.urls import path
from . import views

app_name = 'recipe'

urlpatterns = [
    path('<int:pk>/', views.RecipeDetail.as_view(), name='recipe_detail'),
    path('', views.RecipeList.as_view(), name='recipe_list'),

    path('create/form_1', views.recipe_create_1, name='recipe_create_1'),
    path('create/form_2', views.recipe_create_2, name='recipe_create_2'),
    path('create/form_3', views.recipe_create_3, name='recipe_create_3'),
    path('create/form_4', views.recipe_create_4, name='recipe_create_4'),
    path('create/form_5', views.recipe_create_5, name='recipe_create_5'),

    path('edit/<int:pk>', views.RecipeDetailEdit.as_view(), name='recipe_update'),
    path('delete/<int:pk>', views.RecipeDelete.as_view(), name='recipe_delete'),

    path('title_update/<int:pk>', views.TitleUpdate.as_view(), name='title_update'),
    path('content_update/<int:pk>', views.ContentUpdate.as_view(), name='content_update'),
    path('image_update/<int:pk>', views.ImageUpdate.as_view(), name='image_update'),

    path('ingredients_update/<int:pk>', views.IngredientUpdate.as_view(), name='ingredient_update'),
    path('ingredients_update_empty/<int:pk>', views.IngredientUpdateWithExtra.as_view(), name='ingredient_update_empty'),

    path('tag_update/<int:pk>', views.TagUpdate.as_view(), name='tag_update'),
    path('tag_update_empty/<int:pk>', views.TagUpdateWithExtra.as_view(), name='tag_update_empty'),

    path('comment_update/<int:pk>', views.CommentUpdate.as_view(), name='comment_update'),
    path('comment_delete/<int:pk>', views.CommentDelete.as_view(), name='comment_delete'),



]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('profile/<int:pk>/', views.UserDetail.as_view(), name='user_profile'),
    path('list', views.UserList.as_view(), name='user_list'),
    path('signup', views.UserCreate.as_view(), name='signup'),
    path('user-edit/<int:pk>', views.UserUpdate.as_view(), name='user_update'),
    path('delete-profile/<int:pk>', views.UserDelete.as_view(), name='user_delete'),

    path('edit-profile/<int:pk>', views.UserProfileUpdate.as_view(), name='profile_update'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- CSS -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
              integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
              crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Amatic+SC">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
        <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
        {% block head %}{% endblock %}

        <title>📖 {% block title %}{% endblock %}</title>
  </head>
  <body>
        {% block messages %}{% endblock %}

        <section class="container h-100 my-3 py-2 px-3">
            {% block logo %}{% endblock %}
        </section>

        <section class="container h-100 my-3 py-0 px-3">
            {% block dropdown %}

            {% endblock %}
        </section>

        <section class="container h-100 my-3 py-2 px-3">

            <h1 class="mb-4">{% block header %}{% endblock %}</h1>

            {% block content %}

            {% endblock %}
        </section>

        {% block extra-content %}

        {% endblock %}

        <section class="container footer h-100 my-3 py-2 px-3">
            {% block footer %}

            {% endblock %}
        </section>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        {% block javascript %}{% endblock %}
  </body>
</html>

templates/base_evolved.html
{% extends 'base.html' %}
{% load static %}

{% block logo %}
<a href="{% url 'Home' %}">
    <div class="addable-md">
        <div class="d-flex justify-content-center">
            <img src="{% static 'images/Logo.png' %}">
        </div>
    </div>
    <div class="removable-md">
        <div class="d-flex align-items-center">
            <img src="{% static 'images/Logo.png' %}">
            <h1 class="px-2 my-0">CookBook</h1>
        </div>
    </div>
</a>
{% endblock %}

{% block messages %}
    {% for message in messages %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{ message | safe }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endfor %}
{% endblock %}

{% block dropdown %}
    <div class="dropdown">
        <div class="btn-group">
            <button class="btn btn-secondary dropdown-toggle dropdown-toggle-split" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Recipes
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a href="{% url 'recipe:recipe_list' %}" class="dropdown-item">All recipes</a>
                {% if user.is_authenticated %}
                  <a href="{% url 'recipe:recipe_create_1' %}" class="dropdown-item">Create new recipe</a>
              {% endif %}
            </div>
        </div>
        <div class="btn-group menu-right">
              {% if user.is_authenticated %}
                  <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      {{user.username}}
                  </button>
                  <div class="dropdown-menu dropdown-menu-right">
                      <a href="{% url 'user:user_profile' user.pk %}"class="dropdown-item">Your profile</a>
                          {% if user.is_staff %}
                          <a href="{% url 'user:user_list' %}"class="dropdown-item">User list</a>
                          <a href="{% url 'admin:index' %}"class="dropdown-item">Administration</a>
                          {% endif %}
                      <a href="{% url 'logout' %}"class="dropdown-item">Logout</a>
                  </div>
              {% else %}
                  <a href="{% url 'user:signup' %}"class="btn-secondary btn">Signup</a>
                  <a href="{% url 'login' %}"class="btn-secondary btn">Login</a>
              {% endif %}
        </div>
    </div>
{% endblock %}

{% block footer %}

     <div class="row text-center addable-md mb-3">
         Published in 2022 by Chiara Calzolari for her Web Technologies Exam
    </div>
    <div class="row">
        <div class="col col-6 border-right removable-md">
            <span class="removable-sm">Published in 2022 by Chiara Calzolari for her Web Technologies Exam</span>
        </div>
        <div class="col border-right text-center">
            <a href="https://gitlab.com/Cookie-CHR/cookbook" class="removable-md">Follow the project on GitLab</a>
            <a href="https://gitlab.com/Cookie-CHR/cookbook" class="addable-md">GitLab</a>
        </div>
        <div class="col text-center">
            <a href=# class="removable-md">Another random link</a>
            <a href=# class="addable-md">Link</a>
        </div>
    </div>
    <div class="opacity-50 text-center mt-3">Copyrights and such - All rights reserved, blah blah blah</div>
{% endblock %}

templates/base_list.html
{% extends 'base_evolved.html' %}

{% block title %}{% block list_title %}{% endblock %}{% endblock %}

{% block header %}
{% block list_header %}{% endblock %}
{% endblock %}

{% block content %}
    {% block prev_extra %}{% endblock %}
    {% block list_content %}{% endblock %}
    {% block post_extra %}{% endblock %}
{% endblock %}

templates/base_manipulate.html
{% extends 'base_evolved.html' %}
{% load crispy_forms_tags %}


{% block content %}
    {% block extras %}{% endblock %}
    <form id="form" method="post" enctype='multipart/form-data'>{% csrf_token %}
        {{ form|crispy }}
        {% block form_extras %}{% endblock %}
        {% block form_buttons %}{% endblock %}
    </form>
{% endblock %}

templates/home.html
{% extends 'base_evolved.html' %}
{% load static %}
{% load ratings %}

{% block title %} CookBook - home page {% endblock %}

{% block header %}
Welcome to CookBook
{% endblock %}

{% block content %}
    <p>Cookbook is an online recipe website where everyone can visualize, publish and comment his recipes.</p>
    <a href="{% url 'recipe:recipe_list' %}" class="btn mb-5"><i class="bi bi-book"></i><span class="removable-sm"> Recipe list</span></a>
    <h2 class="amatic">New recipes</h2>
    <div class="row center align-items-center mb-5">
        {% for recipe in newest %}
            <a href="{% url 'recipe:recipe_detail' recipe.pk %}" class="col-md-3 col-sm-6 p-1">
                <div class="card">
                    {% if not recipe.image %}
                        <img class="card-img-top center default-image" src="{% static 'images/Logo.png' %}">
                    {% else %}
                        <img class="card-img-top center" src='{{ recipe.image.url }}' alt="Card image cap">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{recipe.title}}</h5>
                        <p class="card-text font-italic">{{recipe.author}}</p>
                        {% ratings recipe %}
                    </div>
                </div>
            </a>
        {% endfor %}
    </div>

    <h2 class="amatic">Most rated recipes</h2>
    <div class="row center align-items-center mb-5">
        {% for recipe in rated %}
            <a href="{% url 'recipe:recipe_detail' recipe.pk %}" class="col-md-3 col-sm-6 p-1">
                <div class="card">
                    {% if not recipe.image %}
                        <img class="card-img-top center default-image" src="{% static 'images/Logo.png' %}">
                    {% else %}
                        <img class="card-img-top center" src='{{ recipe.image.url }}' alt="Card image cap">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{recipe.title}}</h5>
                        <p class="card-text font-italic">{{recipe.author}}</p>
                        {% ratings recipe %}
                    </div>
                </div>
            </a>
        {% endfor %}
    </div>
{% endblock %}

templates/maintenance.html
{% extends 'base_evolved.html' %}

{% block title %} Maintenance {% endblock %}

{% block header %}
Maintenance
{% endblock %}

{% block content %}
<p>This website is under maintenance!</p>
<p>Service will be back soon.</p>
{% endblock %}