CookBook/urls.py
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),

    path('', views.Home.as_view(), name='Home'),
    path('admin/', admin.site.urls),
    path('maintenance', views.Maintenance.as_view(), name='Maintenance'),
    path('recipe/', include('recipe.urls')),
    path('user/', include('user.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
]

recipe/urls.py
from django.urls import path
from . import views

app_name = 'recipe'

urlpatterns = [
    path('<int:pk>/', views.RecipeDetail.as_view(), name='recipe_detail'),
    path('', views.RecipeList.as_view(), name='recipe_list'),

    path('create/form_1', views.recipe_create_1, name='recipe_create_1'),
    path('create/form_2', views.recipe_create_2, name='recipe_create_2'),
    path('create/form_3', views.recipe_create_3, name='recipe_create_3'),
    path('create/form_4', views.recipe_create_4, name='recipe_create_4'),
    path('create/form_5', views.recipe_create_5, name='recipe_create_5'),

    path('edit/<int:pk>', views.RecipeDetailEdit.as_view(), name='recipe_update'),
    path('delete/<int:pk>', views.RecipeDelete.as_view(), name='recipe_delete'),

    path('title_update/<int:pk>', views.TitleUpdate.as_view(), name='title_update'),
    path('content_update/<int:pk>', views.ContentUpdate.as_view(), name='content_update'),
    path('image_update/<int:pk>', views.ImageUpdate.as_view(), name='image_update'),

    path('ingredients_update/<int:pk>', views.IngredientUpdate.as_view(), name='ingredient_update'),
    path('ingredients_update_empty/<int:pk>', views.IngredientUpdateWithExtra.as_view(), name='ingredient_update_empty'),

    path('tag_update/<int:pk>', views.TagUpdate.as_view(), name='tag_update'),
    path('tag_update_empty/<int:pk>', views.TagUpdateWithExtra.as_view(), name='tag_update_empty'),

    path('comment_update/<int:pk>', views.CommentUpdate.as_view(), name='comment_update'),
    path('comment_delete/<int:pk>', views.CommentDelete.as_view(), name='comment_delete'),



]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('profile/<int:pk>/', views.UserDetail.as_view(), name='user_profile'),
    path('list', views.UserList.as_view(), name='user_list'),
    path('signup', views.UserCreate.as_view(), name='signup'),
    path('user-edit/<int:pk>', views.UserUpdate.as_view(), name='user_update'),
    path('delete-profile/<int:pk>', views.UserDelete.as_view(), name='user_delete'),

    path('edit-profile/<int:pk>', views.UserProfileUpdate.as_view(), name='profile_update'),
]

recipe/forms.py
from django import forms
from django.forms import inlineformset_factory
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, ButtonHolder, Submit

from recipe.models import *


TagsChoices = [
    ("hot_dish",      "Hot dish"),
    ("cold_dish",     "Cold dish"),
    ("appetizer",     "Appetizer"),
    ("first_course",  "First course"),
    ("second_course", "Second course"),
    ("dessert",       "Dessert"),
    ("vegetarian",    "Vegetarian"),
    ("vegan",         "Vegan"),
    ("light",         "Light"),
    ("lactose_free",  "Lactose free"),
    ("gluten_free",   "Gluten free"),
]

IngredientsDistinct = list(IngredientOf.objects.values_list('name', flat=True).distinct().order_by('name'))
IngredientChoices = [(a, a) for a in IngredientsDistinct]


OrderByChoices = [
    ("creation_date",   "Creation date"),
    ("title",           "Title"),
    ("ratings__average",          "Rating"),
]


class TitleForm(forms.ModelForm):
    class Meta:
        model = RecipePost
        fields = ['title']


class ContentForm(forms.ModelForm):
    class Meta:
        model = RecipePost
        fields = ['content']


class ImageForm(forms.ModelForm):
    class Meta:
        model = RecipePost
        fields = ['image']


class TagForm(forms.ModelForm):
    tagname = forms.CharField(label='Tags: ', widget=forms.Select(choices=TagsChoices))

    class Meta:
        model = TagOf
        fields = ['tagname']
        unique_together = ('tagname', 'post',)


TagFormSet = inlineformset_factory(parent_model=RecipePost, model=TagOf, form=TagForm, extra=1, can_delete=True)
TagFormSetWithoutExtras = inlineformset_factory(parent_model=RecipePost, model=TagOf, form=TagForm, extra=0, can_delete=True)


class IngredientForm(forms.ModelForm):
    class Meta:
        model = IngredientOf
        fields = ['name', 'quantity']

    def clean(self):
        """
        ensure that ingredient name is always lower case.
        """

        cleaned_data = self.cleaned_data

        if any(self.errors):
            return

        cleaned_data['name'] = cleaned_data['name'].lower()

        return cleaned_data



IngredientFormSet = inlineformset_factory(parent_model=RecipePost, model=IngredientOf, form=IngredientForm, extra=1, can_delete=True)
IngredientFormSetWithoutExtras = inlineformset_factory(parent_model=RecipePost, model=IngredientOf, form=IngredientForm, extra=0, can_delete=True)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']


class FilterForm(forms.Form):
    search = forms.CharField(required=False)
    filter_tags = forms.MultipleChoiceField(choices=TagsChoices, widget=forms.CheckboxSelectMultiple())
    filter_ingredients = forms.MultipleChoiceField(choices=IngredientChoices, widget=forms.CheckboxSelectMultiple())
    order_by = forms.CharField(label='Order by: ', widget=forms.Select(choices=OrderByChoices))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Div('search'),
            Div(
                Div('filter_tags', css_class='col-sm-6'),
                Div('filter_ingredients', css_class='col-sm-6'),
                css_class='row'
            ),
            Div('order_by'),

            ButtonHolder(
                Submit('submit', 'Submit', css_class='button white')
            )
        )

recipe/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from recipe.models import *
from recipe.forms import *
from django.contrib import messages
from django.views.generic.edit import FormMixin
from CookBook.recommends import recommended
from user.models import UserProfile


# Create your views here.


class RecipeDetail(FormMixin, DetailView):
    model = RecipePost
    template_name = "recipe_detail.html"
    form_class = CommentForm

    def get_success_url(self):
        object = self.get_object()
        return reverse_lazy('recipe:recipe_detail', kwargs={'pk': object.pk})

    def get_context_data(self, **kwargs):
        context = super(RecipeDetail, self).get_context_data(**kwargs)  # get the default context data
        context['ingredients'] = IngredientOf.objects.filter(recipe=self.get_object())
        context['tags'] = TagOf.objects.filter(post=self.get_object()).order_by('tagname')
        context['comments'] = Comment.objects.filter(post=self.get_object())
        context['form'] = CommentForm(initial={'post': self.object})

        context['recommended'] = recommended(self.get_object())
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        form.instance.author = UserProfile.objects.get(user=self.request.user.pk)
        form.instance.post = self.object

        if form.is_valid():
            messages.success(request, 'Commented successfully!')
            return self.form_valid(form)
        else:
            messages.error(request, form.errors.as_data())
            return self.render_to_response(self.get_context_data(form=form))

    def form_valid(self, form):
        form.save()
        return super(RecipeDetail, self).form_valid(form)


class RecipeDetailEdit(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = RecipePost
    template_name = "recipe_detail_edit.html"
    success_url = reverse_lazy('recipe:recipe_list')

    def test_func(self):
        obj = self.get_object()
        return obj.author.user.pk == self.request.user.pk or self.request.user.is_staff

    def get_context_data(self, **kwargs):
        context = super(RecipeDetailEdit, self).get_context_data(**kwargs)  # get the default context data
        context['ingredients'] = IngredientOf.objects.filter(recipe=self.get_object())
        context['tags'] = TagOf.objects.filter(post=self.get_object()).order_by('tagname')
        return context


class RecipeList(ListView):
    model = RecipePost
    template_name = "recipe_list.html"

    def get_context_data(self, **kwargs):
        context = super(RecipeList, self).get_context_data(**kwargs)  # get the default context data
        context['newest'] = RecipePost.objects.order_by('-creation_date')[:4]
        context['rated'] = RecipePost.objects.order_by("-ratings__average")[:4]
        context['all'] = RecipePost.objects.order_by("-ratings__average")
        context['form'] = FilterForm(initial={
            'search': self.request.GET.get('search', ''),
            'filter_tags': self.request.GET.get('filter_tags', ''),
            'filter_ingredients': self.request.GET.get('filter_ingredients', ''),
            'order_by': self.request.GET.get('order_by', ''),
        })
        return context

    def get_queryset(self):
        query = self.request.GET.get('search')
        filter_tags = self.request.GET.get('filter_tags')
        filter_ingredients = self.request.GET.get('filter_ingredients')
        order_by = self.request.GET.get('order_by')

        results = RecipePost.objects.all()
        if query:
            results = results.filter(title__contains=query)
        if filter_tags:
            filtered_tags = TagOf.objects.filter(tagname=filter_tags)
            filtered_posts = filtered_tags.values_list('post', flat=True)
            results = results.filter(pk__in=filtered_posts)
        if filter_ingredients:
            filtered_ingredients = IngredientOf.objects.filter(name=filter_ingredients)
            filtered_posts = filtered_ingredients.values_list('recipe', flat=True)
            results = results.filter(pk__in=filtered_posts)
        if order_by:
            results = results.order_by(order_by)
            if order_by == "ratings__average" or order_by == "creation_date":
                results = results.order_by("-"+order_by)
        return results


def recipe_create_1(request):
    initial = {'title': request.session.get('title', None)}
    form = TitleForm(request.POST or None, initial=initial)
    if request.method == 'POST':
        if form.is_valid():
            request.session['title'] = form.cleaned_data['title']
            return HttpResponseRedirect(reverse_lazy('recipe:recipe_create_2'))
    return render(request, 'recipe_create_1.html', {'form': form})


def recipe_create_2(request):
    formset = IngredientFormSet(request.POST or None)
    if request.method == 'POST':
        if formset.is_valid():
            request.session['ingredients'] = []
            for f in formset:
                if f not in formset.deleted_forms:
                    try:
                        f_dict = {'name': f.cleaned_data['name'], 'quantity': f.cleaned_data['quantity']}
                        request.session['ingredients'].append(f_dict)
                    except KeyError:
                        messages.error(request, "Some ingredient fields are empty: if you want to delete them, check the 'Delete' sign")
                        return render(request, 'recipe_create_2.html', {'form': formset, messages: messages})
            return HttpResponseRedirect(reverse_lazy('recipe:recipe_create_3'))
        else:
            for message in formset.errors:
                messages.error(request, message.as_data())
    return render(request, 'recipe_create_2.html', {'form': formset, messages: messages})


def recipe_create_3(request):
    initial = {
        'content': request.session.get('content', None),
    }
    form = ContentForm(request.POST or None, initial=initial)
    if request.method == 'POST':
        if form.is_valid():
            request.session['content'] = form.cleaned_data['content']
            return HttpResponseRedirect(reverse_lazy('recipe:recipe_create_4'))
        else:
            messages.error(request, form.errors.as_data())
    return render(request, 'recipe_create_3.html', {'form': form})


def recipe_create_4(request):
    formset = TagFormSet(request.POST or None)
    if request.method == 'POST':
        if formset.is_valid():
            request.session['tags'] = []
            for f in formset:
                if f not in formset.deleted_forms:
                    f_dict = {'tagname': f.cleaned_data['tagname']}
                    request.session['tags'].append(f_dict)
            return HttpResponseRedirect(reverse_lazy('recipe:recipe_create_5'))
        else:
            for message in formset.errors:
                messages.error(request, message.as_data())
    return render(request, 'recipe_create_4.html', {'form': formset, messages: messages})


def recipe_create_5(request):
    form = ImageForm(request.POST or None, request.FILES or None)
    if request.method == 'POST':
        if form.is_valid():
            recipe = form.save(commit=False)
            recipe.author = UserProfile.objects.get(user=request.user.pk)
            recipe.title = request.session['title']
            recipe.content = request.session['content']
            recipe.image = form.cleaned_data['image']
            recipe.save()

            for ingredient in request.session['ingredients']:
                IngredientOf.objects.create(name=ingredient.get("name"),
                                            quantity=ingredient.get("quantity"),
                                            recipe=recipe)
            for tag in request.session['tags']:
                TagOf.objects.create(tagname=tag.get("tagname"),
                                     post=recipe)

            messages.success(request, 'Recipe added successfully!')
            return HttpResponseRedirect(reverse_lazy('recipe:recipe_detail', kwargs={'pk': recipe.pk}))
        else:
            messages.error(request, form.errors.as_data())
    return render(request, 'recipe_create_5.html', {'form': form})


class RecipeDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = RecipePost
    template_name = "recipe_delete.html"
    success_url = reverse_lazy('recipe:recipe_list')

    def test_func(self):
        obj = self.get_object()
        return obj.author.user.pk == self.request.user.pk or self.request.user.is_staff


class CommentUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Comment
    form_class = CommentForm
    template_name = "comment_update.html"

    def test_func(self):
        obj = self.get_object()
        return obj.author.user.pk == self.request.user.pk or self.request.user.is_staff

    def get_success_url(self):
        object = self.get_object()
        return reverse_lazy('recipe:recipe_detail', kwargs={'pk': object.post.pk})

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()

        if form.is_valid():
            messages.success(request, 'Comment updated successfully!')
            return self.form_valid(form)
        else:
            messages.error(request, form.errors.as_data())
            return self.render_to_response(self.get_context_data(form=form))


class CommentDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Comment
    template_name = "comment_delete.html"

    def test_func(self):
        obj = self.get_object()

recipe/templates/content_update.html
{% extends 'base_manipulate.html' %}

{% block title %} Edit content {% endblock %}

{% block header %}
Edit content
{% endblock %}

{% block form_buttons %}
    <button type="submit"><i class="bi bi-check-lg"></i> Confirm</button>
    <a href="{% url 'recipe:recipe_update' object.pk %}"><button type="button"><i class="bi bi-x-lg"></i><span class="removable-sm"> Undo</span></button></a>
{% endblock %}

recipe/templates/image_update.html
{% extends 'base_manipulate.html' %}

{% block title %} Edit image {% endblock %}

{% block header %}
Edit image
{% endblock %}

{% block form_buttons %}
    <button type="submit"><i class="bi bi-check-lg"></i> Confirm</button>
    <a href="{% url 'recipe:recipe_update' object.pk %}"><button type="button"><i class="bi bi-x-lg"></i><span class="removable-sm"> Undo</span></button></a>
{% endblock %}

recipe/templates/ingredient_update.html
{% extends 'base_evolved.html' %}
{% load crispy_forms_tags %}

{% block title %} Edit ingredient {% endblock %}

{% block header %}
Edit ingredient
{% endblock %}

{% block content %}
    <form id="form" method="post" enctype='multipart/form-data' autocomplete="off">{% csrf_token %}
        {{form.management_form}}
        {% for f in form %}
        <div class="form-div">{{ f|crispy }}</div>
        {% endfor %}
        <button id="add-form" type="button"><i class="bi bi-plus-lg"></i> Add another ingredient</button>
        <br><br>
        <button type="submit"><i class="bi bi-check-lg"></i> Confirm</button>
        <a href="{% url 'recipe:recipe_update' object.pk %}"><button type="button"><i class="bi bi-x-lg"></i><span class="removable-sm"> Undo</span></button></a>
    </form>
{% endblock %}


{% block javascript %}
    <script>
        let form = document.querySelectorAll(".form-div")
        let container = document.querySelector("#form")
        let addButton = document.querySelector("#add-form")
        let totalForms = document.querySelector("#id_ingredientof_set-TOTAL_FORMS")
        let formNum = form.length-1

        addButton.addEventListener('click', addForm)

        function addForm(e) {
            e.preventDefault()

            let newForm = form[0].cloneNode(true) //Clone the initial form
            let formRegex = RegExp(`ingredientof_set-(\\d){1}`,'g') //Regex to find all instances of the form number

            formNum++ //Increment the form number
            newForm.innerHTML = newForm.innerHTML.replace(formRegex, `ingredientof_set-${formNum}`)
            //Update the new form to have the correct form number
            container.insertBefore(newForm, addButton) //Insert the new form at the end of the list of forms

            totalForms.setAttribute('value', `${formNum+1}`) //Increment the number of total forms in the management form
        }
    </script>
{% endblock %}

recipe/templates/recipe_detail.html
{% extends 'base_evolved.html' %}
{% load crispy_forms_tags %}
{% load ratings %}
{% load static %}

{% block title %} {{object.title|capfirst}} {% endblock %}

{% block header %}
{{object.title|capfirst}}
{% endblock %}

{% block content %}
    <a href="{% url 'recipe:recipe_list' %}" class="btn btn-primary"><i class="bi bi-arrow-left"></i><span class="removable-md"> Back to recipe list</span></a>
    {% if user.is_staff or user == object.author.user %}
        <td class="menu-right">
            <a href="{% url 'recipe:recipe_update' object.pk %}" class="btn btn-primary btn-edit"><i class="bi bi-pencil"></i>Edit recipe</a>
            <a href="{% url 'recipe:recipe_delete' object.pk %}" class="btn btn-primary btn-delete"><i class="bi bi-trash"></i>Delete recipe</a>
        </td>
    {% endif %}

    <div class="mt-5">
        <h2 class="amatic">Ingredients:</h2>
        <table class="ingredients-table">
            {% if ingredients %}
                {% for i in ingredients %}
                    <tr>
                        <td><b>{{ i.name }}</b></td>
                        <td>{{ i.quantity }}</td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr class="mx-3">This recipe has no ingredients. How is that even possible?</tr>
            {% endif %}
        </table>
    </div>

    <div class="mt-5">
        {% if object.image %}
            <div class="row">
                <div class="col-lg-8 col-md-12">
                    <h2 class="amatic">Procedure:</h2>
                    {% if object.content %}
                        <p class="text-justify multiline">{{object.content}}</p>
                    {% else %}
                        <p class="mx-3">This recipe has no content. How is that even possible?</p>
                    {% endif %}
                </div>
                <div class="col-lg-4 col-md-12">
                    <img class="d-flex justify-content-center" src='{{ object.image.url }}' style="width:100%; height:auto">
                </div>
            </div>
        {% else %}
            <h2 class="amatic">Procedure:</h2>
            {% if object.content %}
                <p class="text-justify multiline mb-0">{{object.content}}</p>
            {% else %}
                <p class="mx-3">This recipe has no content. How is that even possible?</p>
            {% endif %}
        {% endif %}

        <div class="author-div d-flex align-items-center mt-2">
            {% if not object.author.picture %}
                <img class="round center default-image profile-pic-md" src="https://heliosgarden.it/wp-content/plugins/all-in-one-seo-pack/images/default-user-image.png">
            {% else %}
                <img class="round center profile-pic-md" src='{{ object.author.picture.url }}'>
            {% endif %}
            <a href="{% url 'user:user_profile' object.author.user.pk %}"><span class="font-italic ml-2">{{object.author}}</span></a>
        </div>
    </div>

    <div class="mt-5">
        <h2 class="amatic">Tags:</h2>
        {% if tags %}
            {% for t in tags %}
                <span class="btn">{{t.tagname}}</span>
            {% endfor %}
        {% else %}
            <p class="mx-3">This recipe has no tags</p>
        {% endif %}
    </div>
    <div class="mt-5">
        <h2 class="amatic">Rate this recipe</h2>
        {% ratings object %}
    </div>
{% endblock %}

{% block extra-content %}
    <section class="container h-100 my-3 py-2 px-3">
        <h1 class="mb-4">Comments</h1>

        {% if comments %}
            {% for c in comments %}
                <div class="comment m-2 p-2">
                    <div class="comment-header">
                            {% if not c.author.picture %}
                                <img class="round center default-image profile-pic-sm" src="https://heliosgarden.it/wp-content/plugins/all-in-one-seo-pack/images/default-user-image.png">
                            {% else %}
                                <img class="round center profile-pic-sm" src='{{ c.author.picture.url }}'>
                            {% endif %}
                        <span class="font-italic">{{c.author}}</span>
                        {% if user.is_staff or user == c.author.user %}
                            <span class="menu-right">
                                <a href="{% url 'recipe:comment_update' c.pk %}" class="btn btn-primary btn-edit"><i class="bi bi-pencil"></i></a>
                                <a href="{% url 'recipe:comment_delete' c.pk %}" class="btn btn-primary btn-delete"><i class="bi bi-trash"></i></a>
                            </span>
                        {% endif %}
                    </div>
                    <p class="text-justify multiline">{{c.text}}</p>
                </div>
            {% endfor %}
        {% else %}
            <p class="mx-3">There are no comments in this recipe yet. Be the first to write one!</p>
        {% endif %}

        <h1 class="mb-4">Write your comment</h1>

        {% if user.is_authenticated %}
        <form method="post">{% csrf_token %}
            {{ form|crispy }}
            <button type="submit"><i class="bi bi-check-lg"></i> Confirm</button>
        </form>
        {% else %}
            <p class="mx-3">You must be registered to send a comment. <a href="{% url 'user:signup' %}">Sign up now!</a></p>
        {% endif %}

    </section>

    <section class="container h-100 my-3 py-2 px-3">
        <h1 class="mb-4">Similar recipes</h1>
        <div class="row center align-items-center mb-4">
            {% for recipe in recommended %}
                <a href="{% url 'recipe:recipe_detail' recipe.pk %}" class="col-md-3 col-sm-6 p-1">
                    <div class="card">
                        {% if not recipe.image %}
                            <img class="card-img-top center default-image" src="{% static 'images/Logo.png' %}">
                        {% else %}
                            <img class="card-img-top center" src='{{ recipe.image.url }}' alt="Card image cap">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{recipe.title}}</h5>
                            <p class="card-text font-italic">{{recipe.author}}</p>
                            {% ratings recipe %}
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>
    </section>
{% endblock %}

recipe/templates/recipe_list.html
{% extends 'base_list.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load ratings %}

{% block list_title %} Recipes {% endblock %}

{% block list_header %}
Recipes
{% endblock %}

{% block list_content %}
    <button class="mb-3" onclick="toggleSearch()">Advanced search</button>
    <form id="SearchForm" class="toggledown">
        {% crispy form form.helper %}
    </form>

    {% if form.has_changed %}
    <h2 class="amatic">Recipes that matched your search</h2>
    <div class="row center align-items-center mb-5">
        {% if object_list%}
            {% for recipe in object_list %}
                <a href="{% url 'recipe:recipe_detail' recipe.pk %}" class="col-md-3 col-sm-6 p-1">
                    <div class="card">
                        {% if not recipe.image %}
                            <img class="card-img-top center default-image" src="{% static 'images/Logo.png' %}">
                        {% else %}
                            <img class="card-img-top center" src='{{ recipe.image.url }}' alt="Card image cap">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{recipe.title}}</h5>
                            <p class="card-text font-italic">{{recipe.author}}</p>
                            {% ratings recipe %}
                        </div>
                    </div>
                </a>
            {% endfor %}
        {% else %}
            <p class="mx-3">No recipes matched your research</p>
        {% endif %}
    </div>
    {% endif %}

    <h2 class="amatic">New recipes</h2>
    <div class="row center align-items-center mb-5">
        {% for recipe in newest %}
            <a href="{% url 'recipe:recipe_detail' recipe.pk %}" class="col-md-3 col-sm-6 p-1">
                <div class="card">
                    {% if not recipe.image %}
                        <img class="card-img-top center default-image" src="{% static 'images/Logo.png' %}">
                    {% else %}
                        <img class="card-img-top center" src='{{ recipe.image.url }}' alt="Card image cap">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{recipe.title}}</h5>
                        <p class="card-text font-italic">{{recipe.author}}</p>
                        {% ratings recipe %}
                        </div>
                </div>
            </a>
        {% endfor %}
    </div>

    <h2 class="amatic">Most rated recipes</h2>
    <div class="row center align-items-center mb-5">
        {% for recipe in rated %}
            <a href="{% url 'recipe:recipe_detail' recipe.pk %}" class="col-md-3 col-sm-6 p-1">
                <div class="card">
                    {% if not recipe.image %}
                        <img class="card-img-top center default-image" src="{% static 'images/Logo.png' %}">
                    {% else %}
                        <img class="card-img-top center" src='{{ recipe.image.url }}' alt="Card image cap">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{recipe.title}}</h5>
                        <p class="card-text font-italic">{{recipe.author}}</p>
                        {% ratings recipe %}
                    </div>
                </div>
            </a>
        {% endfor %}
    </div>

    <h2 class="amatic">All recipes</h2>
    <div class="row center align-items-center mb-4">
        {% for recipe in all %}
            <a href="{% url 'recipe:recipe_detail' recipe.pk %}" class="col-md-3 col-sm-6 p-1">
                <div class="card">
                    {% if not recipe.image %}
                        <img class="card-img-top center default-image" src="{% static 'images/Logo.png' %}">
                    {% else %}
                        <img class="card-img-top center" src='{{ recipe.image.url }}' alt="Card image cap">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{recipe.title}}</h5>
                        <p class="card-text font-italic">{{recipe.author}}</p>
                        {% ratings recipe %}
                    </div>
                </div>
            </a>
        {% endfor %}
    </div>

    <script>
        function toggleSearch(){
          var x = document.getElementById("SearchForm");
          if (x.style.display === "none") {
            x.style.display = "block";
          } else {
            x.style.display = "none";
          }
        }
    </script>
{% endblock %}

{% block post_extra %}
    <a href="{% url 'recipe:recipe_create_1' %}" class="btn btn-primary mt-4"><i class="bi bi-plus-lg"></i><span class="removable-md"> New recipe</span></a>
{% endblock %}

recipe/templates/recipe_update.html
{% extends 'base_evolved.html' %}
{% load crispy_forms_tags %}

{% block title %} Edit Recipe {% endblock %}

{% block header %}
Edit recipe
{% endblock %}

{% block content %}
    <form method="post">{% csrf_token %}
        <p>Ingredients*</p>
        {% for i in formset %}
            <div>{{i}}</div>
        {% endfor %}
        <br>
        {{ form|crispy }}

        <button type="submit"><i class="bi bi-check-lg"></i> Confirm</button>
        <a href="{% url 'recipe:recipe_update' object.pk %}"><button type="button"><i class="bi bi-x-lg"></i><span class="removable-sm"> Undo</span></button></a>
    </form>
{% endblock %}

recipe/templates/title_update.html
{% extends 'base_manipulate.html' %}

{% block title %} Edit title {% endblock %}

{% block header %}
Edit title
{% endblock %}

{% block form_buttons %}
    <button type="submit"><i class="bi bi-check-lg"></i> Confirm</button>
    <a href="{% url 'recipe:recipe_update' object.pk %}"><button type="button"><i class="bi bi-x-lg"></i><span class="removable-sm"> Undo</span></button></a>
{% endblock %}